name: dribbble_sushi_bar_challenge
description: "Dribbble sushi bar challenge"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_animate: ^4.4.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  bloc_test: ^9.1.5
  device_preview: ^1.1.0
  gap: any
  rive: ^0.12.4
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600

flutter_intl:
  enabled: true
  class_name: L10n
  arb_dir: assets/l10n
  output_dir: lib/translations